version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backtesting-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:///app/data/backtesting.db
      # JWT usa SECRET_KEY, no JWT_SECRET
      - SECRET_KEY=${SECRET_KEY:-[<fv,5a6*PS)liZHOe5d[]Ljms>BO=J]-f]6w#u%mPe)tJ5MG^tA4D_|&]hs|P>&}
    volumes:
      - ./backend/data:/app/data
    networks:
      - backtesting-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: backtesting-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - backtesting-network
    restart: unless-stopped

networks:
  backtesting-network:
    driver: bridge
