version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:///app/data/backtesting.db
      - SECRET_KEY=[<fv,5a6*PS)liZHOe5d[]Ljms>BO=J]-f]6w#u%mPe)tJ5MG^tA4D_|&]hs|P>&
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    networks:
      - backtesting-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - backtesting-network
    restart: unless-stopped

# Volumes eliminados - usando bind mount para datos

networks:
  backtesting-network:
    driver: bridge
